export const data = [
  {
    account: "TimberWorks Energy",
    id: "TW304719",
    score: "60%",
    status: "complete",
    country: "canada",
    lastUpdate: "Today at 8:08",
    image: "buildings 2.svg",
  },
  {
    account: "John Smith",
    id: "12345678",
    score: "0%",
    status: "In review",
    country: "Germany",
    lastUpdate: "Last week",
    image: "profile 1.svg",
  },
  {
    account: "Emma Robertson",
    id: "123456789RC0001",
    score: "10%",
    status: "Incomplete",
    country: "Brazil",
    lastUpdate: "2 months ago",
    image: "profile 1.svg",
  },
  {
    account: "CrudeCore Inc.",
    id: "CC541002",
    score: "40%",
    status: "In progress",
    country: "United States",
    lastUpdate: "Last week",
    image: "buildings 2.svg",
  },
  {
    account: "Charles Anderson",
    id: "PBR703822",
    score: "90%",
    status: "complete",
    country: "South Korea",
    lastUpdate: "3 weeks ago",
    image: "profile 1.svg",
  },
  {
    account: "Woodland Constructors",
    id: "WC209635",
    score: "100%",
    status: "complete",
    country: "Australia",
    lastUpdate: "A year ago",
    image: "buildings 2.svg",
  },
  {
    account: "BlackGold Energy Corp.",
    id: "BGEC728419",
    score: "90%",
    status: "complete",
    country: "Saudi Arabia",
    lastUpdate: "Yesterday at 10:16 AM",
    image: "buildings 2.svg",
  },
  {
    account: "Emily Peterson",
    id: "12345678901",
    score: "0%",
    status: "In review",
    country: "Russia",
    lastUpdate: "Last week",
    image: "profile 1.svg",
  },
  {
    account: "PetroPeak Industries",
    id: "PPI611504",
    score: "10%",
    status: "In review",
    country: "United Arab Emirates",
    lastUpdate: "5 days ago",
    image: "buildings 2.svg",
  },
  {
    account: "BuildGreen Forestry Co.",
    id: "BGFC920155",
    score: "100%",
    status: "complete",
    country: "Sweden",
    lastUpdate: "Last month",
    image: "buildings 2.svg",
  },
];
